# Generated by Django 4.2.24 on 2025-09-08 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guilds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guild',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='guild_images/'),
        ),
    ]
